import type { BuildingDefinition } from "./types";

export const buildings: BuildingDefinition[] = [
  {
    id: "campus",
    name: "Campus Overworld",
    tone: "Compact, walkable, bright at first glance, and quietly charged with rumor.",
    accessRequirements: [],
    npcGroups: ["Students", "Facilities", "Wandering geese"],
    interactables: ["Quest board relay", "Fast travel signposts"],
    secrets: ["Hidden rumor trails between buildings"],
    fastTravelLinks: ["library", "north-hall", "south-hall", "main-hall"],
  },
  {
    id: "library",
    name: "Library / IT Operations",
    tone: "Scholarly sanctuary with dead terminals, soft lamp glow, and a basement that remembers too much.",
    accessRequirements: [],
    npcGroups: ["IT Operations", "Archivists"],
    interactables: ["Quest board", "Archive terminals", "Server racks"],
    secrets: ["Basement tunnels", "Cursed stacks", "Old surveillance nodes"],
    fastTravelLinks: ["campus", "north-hall", "south-hall"],
  },
  {
    id: "north-hall",
    name: "North Hall",
    tone: "Lively dorm chaos with stacked rumors, side quests, and a late-night weirdness budget.",
    accessRequirements: [],
    npcGroups: ["Student Residents"],
    interactables: ["Dorm board", "Rumor map", "Lost and found", "Hidden archive room door"],
    secrets: ["Roof access", "Crawlspaces", "Hidden stashes", "VRML-like archive side room"],
    fastTravelLinks: ["campus", "library", "north-hall-archive-room"],
  },
  {
    id: "north-hall-archive-room",
    name: "North Hall Archive Room",
    tone: "A strange little pseudo-3D side room, like an old VRML artifact stapled onto a dorm building.",
    accessRequirements: [],
    npcGroups: ["None"],
    interactables: ["Shelf rows", "Search pulse"],
    secrets: ["Archive Box 17 hidden on a shelf"],
    fastTravelLinks: ["north-hall"],
  },
  {
    id: "south-hall",
    name: "South Hall",
    tone: "A bureaucratic dungeon where access control and social stealth decide your route.",
    accessRequirements: ["south-hall-visitor-badge"],
    npcGroups: ["Administrators", "Student Life"],
    interactables: ["Badge readers", "Locked file rooms", "Admissions desks"],
    secrets: ["Executive side offices", "Hidden meeting rooms"],
    fastTravelLinks: ["campus", "library", "main-hall"],
  },
  {
    id: "main-hall",
    name: "Main Hall",
    tone: "Grand and theatrical, the mythic anchor that keeps the whole map emotionally centered.",
    accessRequirements: ["main-hall-stage-key"],
    npcGroups: ["Performers", "Event staff"],
    interactables: ["Backstage console", "Ceremonial hall doors"],
    secrets: ["Trap doors", "Catwalks", "Forgotten storage"],
    fastTravelLinks: ["campus", "south-hall"],
  },
];
